export const LOCAL_REACTIONS = {
  en: 'Reactions',
  he: 'תגובות',
  hi: 'प्रतिक्रियाओं',
  ar: 'ردود الفعل',
  th: 'ปฏิกิริยา',
  zu: 'Ukusabela',
  'zh-Hant': '反應',
  id: 'Reaksi',
  sk: 'Reakcie',
  da: 'Reaktioner',
  fr: 'Réactions',
  nb: 'Reaksjoner',
  de: 'Reaktionen',
  it: 'Reazioni',
  fi: 'Reaktiot',
  es: 'Reacciones',
  el: 'Αντιδράσεις',
  ja: '反応',
  pl: 'Reakcje',
  cs: 'Reakce',
  ko: '반응',
  nl: 'Reacties',
  ro: 'Reacții',
  hu: 'Reakciók',
  'zh-Hans': '反应',
  tr: 'Tepkiler',
  ru: 'Реакции',
  pt: 'Reações',
  sv: 'Reaktioner',
}
