import type { Prisma } from '@prisma/client'

export const createHN = (user: {
  id?: string
}): Prisma.NewsletterCreateArgs['data'][] => [
  {
    name: 'HN (Afrikaans)',
    handle: 'hn-af',
    keyword: '',
    locale: 'af',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Akan)',
    handle: 'hn-ak',
    keyword: '',
    locale: 'ak',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (አማርኛ)',
    handle: 'hn-am',
    keyword: '',
    locale: 'am',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (العربية)',
    handle: 'hn-ar',
    keyword: '',
    locale: 'ar',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (অসমীয়া)',
    handle: 'hn-as',
    keyword: '',
    locale: 'as',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Aymara)',
    handle: 'hn-ay',
    keyword: '',
    locale: 'ay',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (azərbaycan)',
    handle: 'hn-az',
    keyword: '',
    locale: 'az',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Bashkir)',
    handle: 'hn-ba',
    keyword: '',
    locale: 'ba',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (беларуская)',
    handle: 'hn-be',
    keyword: '',
    locale: 'be',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (български)',
    handle: 'hn-bg',
    keyword: '',
    locale: 'bg',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Bhojpuri)',
    handle: 'hn-bho',
    keyword: '',
    locale: 'bho',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (bamanakan)',
    handle: 'hn-bm',
    keyword: '',
    locale: 'bm',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (বাংলা)',
    handle: 'hn-bn',
    keyword: '',
    locale: 'bn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (བོད་སྐད་)',
    handle: 'hn-bo',
    keyword: '',
    locale: 'bo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (bosanski)',
    handle: 'hn-bs',
    keyword: '',
    locale: 'bs',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (català)',
    handle: 'hn-ca',
    keyword: '',
    locale: 'ca',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Cebuano)',
    handle: 'hn-ceb',
    keyword: '',
    locale: 'ceb',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Kurdish, Sorani)',
    handle: 'hn-ckb',
    keyword: '',
    locale: 'ckb',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Corsican)',
    handle: 'hn-co',
    keyword: '',
    locale: 'co',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (čeština)',
    handle: 'hn-cs',
    keyword: '',
    locale: 'cs',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Cymraeg)',
    handle: 'hn-cy',
    keyword: '',
    locale: 'cy',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (dansk)',
    handle: 'hn-da',
    keyword: '',
    locale: 'da',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Deutsch)',
    handle: 'hn-de',
    keyword: '',
    locale: 'de',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Dogri)',
    handle: 'hn-doi',
    keyword: '',
    locale: 'doi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Dhivehi)',
    handle: 'hn-dv',
    keyword: '',
    locale: 'dv',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (eʋegbe)',
    handle: 'hn-ee',
    keyword: '',
    locale: 'ee',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Ελληνικά)',
    handle: 'hn-el',
    keyword: '',
    locale: 'el',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (English)',
    handle: 'hn-en',
    keyword: '',
    locale: 'en',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (esperanto)',
    handle: 'hn-eo',
    keyword: '',
    locale: 'eo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (español)',
    handle: 'hn-es',
    keyword: '',
    locale: 'es',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (eesti)',
    handle: 'hn-et',
    keyword: '',
    locale: 'et',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (euskara)',
    handle: 'hn-eu',
    keyword: '',
    locale: 'eu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (فارسی)',
    handle: 'hn-fa',
    keyword: '',
    locale: 'fa',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (suomi)',
    handle: 'hn-fi',
    keyword: '',
    locale: 'fi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Filipino, Tagalog)',
    handle: 'hn-fil',
    keyword: '',
    locale: 'fil',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Fijian)',
    handle: 'hn-fj',
    keyword: '',
    locale: 'fj',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (føroyskt)',
    handle: 'hn-fo',
    keyword: '',
    locale: 'fo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (français)',
    handle: 'hn-fr',
    keyword: '',
    locale: 'fr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (West-Frysk)',
    handle: 'hn-fy',
    keyword: '',
    locale: 'fy',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Gaeilge)',
    handle: 'hn-ga',
    keyword: '',
    locale: 'ga',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Gàidhlig)',
    handle: 'hn-gd',
    keyword: '',
    locale: 'gd',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (galego)',
    handle: 'hn-gl',
    keyword: '',
    locale: 'gl',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Guarani)',
    handle: 'hn-gn',
    keyword: '',
    locale: 'gn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Konkani)',
    handle: 'hn-gom',
    keyword: '',
    locale: 'gom',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ગુજરાતી)',
    handle: 'hn-gu',
    keyword: '',
    locale: 'gu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Hausa)',
    handle: 'hn-ha',
    keyword: '',
    locale: 'ha',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Hawaiian)',
    handle: 'hn-haw',
    keyword: '',
    locale: 'haw',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (עברית)',
    handle: 'hn-he',
    keyword: '',
    locale: 'he',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (हिंदी)',
    handle: 'hn-hi',
    keyword: '',
    locale: 'hi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Hmong)',
    handle: 'hn-hmn',
    keyword: '',
    locale: 'hmn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (hrvatski)',
    handle: 'hn-hr',
    keyword: '',
    locale: 'hr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Upper Sorbian)',
    handle: 'hn-hsb',
    keyword: '',
    locale: 'hsb',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Haitian Creole)',
    handle: 'hn-ht',
    keyword: '',
    locale: 'ht',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (magyar)',
    handle: 'hn-hu',
    keyword: '',
    locale: 'hu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (հայերեն)',
    handle: 'hn-hy',
    keyword: '',
    locale: 'hy',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Bahasa Indonesia)',
    handle: 'hn-id',
    keyword: '',
    locale: 'id',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Igbo)',
    handle: 'hn-ig',
    keyword: '',
    locale: 'ig',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Inuinnaqtun)',
    handle: 'hn-ikt',
    keyword: '',
    locale: 'ikt',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Ilocano)',
    handle: 'hn-ilo',
    keyword: '',
    locale: 'ilo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (íslenska)',
    handle: 'hn-is',
    keyword: '',
    locale: 'is',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (italiano)',
    handle: 'hn-it',
    keyword: '',
    locale: 'it',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Inuktitut)',
    handle: 'hn-iu',
    keyword: '',
    locale: 'iu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (日本語)',
    handle: 'hn-ja',
    keyword: '',
    locale: 'ja',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Javanese)',
    handle: 'hn-jv',
    keyword: '',
    locale: 'jv',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ქართული)',
    handle: 'hn-ka',
    keyword: '',
    locale: 'ka',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (қазақ тілі)',
    handle: 'hn-kk',
    keyword: '',
    locale: 'kk',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ខ្មែរ)',
    handle: 'hn-km',
    keyword: '',
    locale: 'km',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Kurdish, Northern)',
    handle: 'hn-kmr',
    keyword: '',
    locale: 'kmr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ಕನ್ನಡ)',
    handle: 'hn-kn',
    keyword: '',
    locale: 'kn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (한국어)',
    handle: 'hn-ko',
    keyword: '',
    locale: 'ko',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Krio)',
    handle: 'hn-kri',
    keyword: '',
    locale: 'kri',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Kurdish)',
    handle: 'hn-ku',
    keyword: '',
    locale: 'ku',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (кыргызча)',
    handle: 'hn-ky',
    keyword: '',
    locale: 'ky',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Latin)',
    handle: 'hn-la',
    keyword: '',
    locale: 'la',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Lëtzebuergesch)',
    handle: 'hn-lb',
    keyword: '',
    locale: 'lb',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Luganda)',
    handle: 'hn-lg',
    keyword: '',
    locale: 'lg',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (lingála)',
    handle: 'hn-ln',
    keyword: '',
    locale: 'ln',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ລາວ)',
    handle: 'hn-lo',
    keyword: '',
    locale: 'lo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (lietuvių)',
    handle: 'hn-lt',
    keyword: '',
    locale: 'lt',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Mizo)',
    handle: 'hn-lus',
    keyword: '',
    locale: 'lus',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (latviešu)',
    handle: 'hn-lv',
    keyword: '',
    locale: 'lv',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Maithili)',
    handle: 'hn-mai',
    keyword: '',
    locale: 'mai',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Malagasy)',
    handle: 'hn-mg',
    keyword: '',
    locale: 'mg',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Maori)',
    handle: 'hn-mi',
    keyword: '',
    locale: 'mi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (македонски)',
    handle: 'hn-mk',
    keyword: '',
    locale: 'mk',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (മലയാളം)',
    handle: 'hn-ml',
    keyword: '',
    locale: 'ml',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (монгол)',
    handle: 'hn-mn',
    keyword: '',
    locale: 'mn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Meiteilon, Manipuri)',
    handle: 'hn-mni',
    keyword: '',
    locale: 'mni',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (मराठी)',
    handle: 'hn-mr',
    keyword: '',
    locale: 'mr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Bahasa Melayu)',
    handle: 'hn-ms',
    keyword: '',
    locale: 'ms',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Malti)',
    handle: 'hn-mt',
    keyword: '',
    locale: 'mt',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Hmong Daw)',
    handle: 'hn-mww',
    keyword: '',
    locale: 'mww',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ဗမာ)',
    handle: 'hn-my',
    keyword: '',
    locale: 'my',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (नेपाली)',
    handle: 'hn-ne',
    keyword: '',
    locale: 'ne',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Nederlands)',
    handle: 'hn-nl',
    keyword: '',
    locale: 'nl',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Norwegian Bokmål)',
    handle: 'hn-nb',
    keyword: '',
    locale: 'nb',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Sepedi)',
    handle: 'hn-nso',
    keyword: '',
    locale: 'nso',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Nyanja, Chichewa)',
    handle: 'hn-ny',
    keyword: '',
    locale: 'ny',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Oromoo)',
    handle: 'hn-om',
    keyword: '',
    locale: 'om',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ଓଡ଼ିଆ)',
    handle: 'hn-or',
    keyword: '',
    locale: 'or',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Queretaro Otomi)',
    handle: 'hn-otq',
    keyword: '',
    locale: 'otq',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ਪੰਜਾਬੀ)',
    handle: 'hn-pa',
    keyword: '',
    locale: 'pa',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (polski)',
    handle: 'hn-pl',
    keyword: '',
    locale: 'pl',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Dari)',
    handle: 'hn-prs',
    keyword: '',
    locale: 'prs',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (پښتو)',
    handle: 'hn-ps',
    keyword: '',
    locale: 'ps',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (português)',
    handle: 'hn-pt',
    keyword: '',
    locale: 'pt',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Runasimi)',
    handle: 'hn-qu',
    keyword: '',
    locale: 'qu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (română)',
    handle: 'hn-ro',
    keyword: '',
    locale: 'ro',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (русский)',
    handle: 'hn-ru',
    keyword: '',
    locale: 'ru',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Kinyarwanda)',
    handle: 'hn-rw',
    keyword: '',
    locale: 'rw',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Sanskrit)',
    handle: 'hn-sa',
    keyword: '',
    locale: 'sa',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Sindhi)',
    handle: 'hn-sd',
    keyword: '',
    locale: 'sd',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (සිංහල)',
    handle: 'hn-si',
    keyword: '',
    locale: 'si',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (slovenčina)',
    handle: 'hn-sk',
    keyword: '',
    locale: 'sk',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (slovenščina)',
    handle: 'hn-sl',
    keyword: '',
    locale: 'sl',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Samoan)',
    handle: 'hn-sm',
    keyword: '',
    locale: 'sm',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (chiShona)',
    handle: 'hn-sn',
    keyword: '',
    locale: 'sn',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Soomaali)',
    handle: 'hn-so',
    keyword: '',
    locale: 'so',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (shqip)',
    handle: 'hn-sq',
    keyword: '',
    locale: 'sq',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (српски)',
    handle: 'hn-sr',
    keyword: '',
    locale: 'sr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Sesotho)',
    handle: 'hn-st',
    keyword: '',
    locale: 'st',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Sundanese)',
    handle: 'hn-su',
    keyword: '',
    locale: 'su',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (svenska)',
    handle: 'hn-sv',
    keyword: '',
    locale: 'sv',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Kiswahili)',
    handle: 'hn-sw',
    keyword: '',
    locale: 'sw',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (தமிழ்)',
    handle: 'hn-ta',
    keyword: '',
    locale: 'ta',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (తెలుగు)',
    handle: 'hn-te',
    keyword: '',
    locale: 'te',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tajik)',
    handle: 'hn-tg',
    keyword: '',
    locale: 'tg',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ไทย)',
    handle: 'hn-th',
    keyword: '',
    locale: 'th',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ትግርኛ)',
    handle: 'hn-ti',
    keyword: '',
    locale: 'ti',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Turkmen)',
    handle: 'hn-tk',
    keyword: '',
    locale: 'tk',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tagalog)',
    handle: 'hn-tl',
    keyword: '',
    locale: 'tl',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (lea fakatonga)',
    handle: 'hn-to',
    keyword: '',
    locale: 'to',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Türkçe)',
    handle: 'hn-tr',
    keyword: '',
    locale: 'tr',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tsonga)',
    handle: 'hn-ts',
    keyword: '',
    locale: 'ts',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tatar)',
    handle: 'hn-tt',
    keyword: '',
    locale: 'tt',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tahitian)',
    handle: 'hn-ty',
    keyword: '',
    locale: 'ty',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ئۇيغۇرچە)',
    handle: 'hn-ug',
    keyword: '',
    locale: 'ug',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (українська)',
    handle: 'hn-uk',
    keyword: '',
    locale: 'uk',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (اردو)',
    handle: 'hn-ur',
    keyword: '',
    locale: 'ur',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (oʻzbekcha)',
    handle: 'hn-uz',
    keyword: '',
    locale: 'uz',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Tiếng Việt)',
    handle: 'hn-vi',
    keyword: '',
    locale: 'vi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Xhosa)',
    handle: 'hn-xh',
    keyword: '',
    locale: 'xh',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (ייִדיש)',
    handle: 'hn-yi',
    keyword: '',
    locale: 'yi',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Èdè Yorùbá)',
    handle: 'hn-yo',
    keyword: '',
    locale: 'yo',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (Yucatec Maya)',
    handle: 'hn-yua',
    keyword: '',
    locale: 'yua',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (中文, 中国香港特别行政区)',
    handle: 'hn-yue',
    keyword: '',
    locale: 'yue',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (中文, 中国)',
    handle: 'hn-zh-CN',
    keyword: '',
    locale: 'zh-CN',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (中文, 台湾)',
    handle: 'hn-zh-TW',
    keyword: '',
    locale: 'zh-TW',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
  {
    name: 'HN (isiZulu)',
    handle: 'hn-zu',
    keyword: '',
    locale: 'zu',
    region: 'US',
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    userId: user?.id ?? '',
  },
]
