export const getAdImgHtml = (imglink?: string, link?: string) => {
  return `<a href=${
    link ?? 'https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7'
  } target="_blank" rel="noopener noreferrer" style="display: flex; justify-content: center; border-radius: 4px; width: 100%; aspect-ratio: 41.67%; max-width: 800px; margin: 0 auto;"><img src="${
    imglink ?? 'https://github.com/anaclumos/heimdall/blob/main/static/img/sponsor-none.png?raw=true'
  }" alt="sponsor" width="480" height="200" style = "width: 100%; height: 100%; object-fit: cover; object-position: center;"/></a>\n\n`
}

const title = {
  en: 'Rahul Pandey on Leaving Meta for Taro: Insights and Surprises',
  cs: 'Rahul Pandey o odchodu z Meta do Taro: postřehy a překvapení',
  nl: 'Rahul Pandey over Meta verlaten voor Taro: inzichten en verrassingen',
  id: 'Rahul Pandey tentang Meninggalkan Meta untuk Taro: Wawasan dan Kejutan',
  ro: 'Rahul Pandey despre plecarea de la Meta pentru Taro: Perspective și surprize',
  da: 'Rahul Pandey om at forlade Meta til fordel for Taro: indsigter og overraskelser',
  de: 'Rahul Pandey über den Wechsel von Meta zu Taro: Einsichten und Überraschungen',
  ja: 'ラフール・パンデイ、メタからタロへ：洞察と驚き',
  fr: "Rahul Pandey sur l'abandon du Meta pour le Taro : réflexions et surprises",
  hu: 'Rahul Pandey a Meta elhagyásáról a Taro számára: felismerések és meglepetések',
  tr: "Rahul Pandey Taro için Meta'dan Ayrılmak Üzerine: İçgörüler ve Sürprizler",
  nb: 'Rahul Pandey om å forlate Meta til fordel for Taro: innsikter og overraskelser',
  sk: 'Rahul Pandey o odchode z Meta do Taro: postrehy a prekvapenia',
  ru: 'Рахул Пандей об уходе из Мета в Таро: выводы и сюрпризы',
  es: 'Rahul Pandey, de Meta a Taro: ideas y sorpresas',
  it: 'Rahul Pandey: "Lasciare Meta per Taro: intuizioni e sorprese".',
  fi: 'Rahul Pandey: Meta lähtee Tarosta: oivalluksia ja yllätyksiä',
  el: 'Ο Rahul Pandey στο αφήνοντας το Meta για το Taro: Διαπιστώσεις και εκπλήξεις',
  'zh-Hans': '拉胡尔-潘迪谈离开 Meta 到太郎：感悟与惊喜',
  sv: 'Rahul Pandey om att lämna Meta för Taro: insikter och överraskningar',
  pl: 'Rahul Pandey o opuszczeniu Meta dla Taro: spostrzeżenia i niespodzianki',
  pt: 'Rahul Pandey sobre a troca do Meta pelo Taro: percepções e surpresas',
  ko: '메타를 떠나 타로로: 인사이트와 놀라움에 대한 라훌 판데이의 이야기',
  ar: 'راهول باندي يتحدث عن مغادرة ميتا ل Taro: رؤى ومفاجآت',
  th: 'Rahul Pandey เกี่ยวกับการออกจาก Meta สําหรับ Taro: ข้อมูลเชิงลึกและความประหลาดใจ',
  he: 'ראהול פנדי על עזיבת מטא לטובת טארו: תובנות והפתעות',
  hi: 'टैरो के लिए मेटा छोड़ने पर राहुल पांडे: अंतर्दृष्टि और आश्चर्य',
  'zh-Hant': '拉胡爾·潘迪 （Rahul Pandey） 談離開 Meta 前往 Taro：見解和驚喜',
  bn: 'মেটা ফর টারো নিয়ে রাহুল পান্ডে: অন্তর্দৃষ্টি এবং বিস্ময়',
  ta: 'மெட்டாவை விட்டு டாரோவுக்கு சென்றது குறித்து ராகுல் பாண்டே: நுண்ணறிவுகள் மற்றும் ஆச்சரியங்கள்',
}

const bulletOne = {
  en: 'Rahul Pandey, the founder and CEO of Taro, shares insights from his experience of leaving a lucrative $800K position at Meta to start his own company.',
  hi: 'टैरो के संस्थापक और सीईओ राहुल पांडे ने अपनी खुद की कंपनी शुरू करने के लिए मेटा में $ 800K की आकर्षक स्थिति छोड़ने के अपने अनुभव से अंतर्दृष्टि साझा की है।',
  th: 'Rahul Pandey ผู้ก่อตั้งและซีอีโอของ Taro แบ่งปันข้อมูลเชิงลึกจากประสบการณ์ของเขาในการออกจากตําแหน่งที่ร่ํารวย $ 800K ที่ Meta เพื่อเริ่มต้นบริษัทของเขาเอง',
  bn: 'তারোর প্রতিষ্ঠাতা এবং সিইও রাহুল পান্ডে মেটায় ৮০০,০ ডলারের লাভজনক পদ ছেড়ে নিজের সংস্থা শুরু করার অভিজ্ঞতা থেকে অন্তর্দৃষ্টি ভাগ করেছেন।',
  he: 'ראהול פנדיי, המייסד והמנכ"ל של תרו, חולק תובנות מניסיונו לעזוב משרה רווחית של 800 אלף דולר במטא כדי להקים חברה משלו.',
  ar: 'يشارك راهول باندي ، المؤسس والرئيس التنفيذي لشركة Taro ، رؤى من تجربته في ترك منصب مربح بقيمة 800 ألف دولار في Meta لبدء شركته الخاصة.',
  ta: 'டாரோவின் நிறுவனர் மற்றும் தலைமை நிர்வாக அதிகாரியான ராகுல் பாண்டே, மெட்டாவில் 800 ஆயிரம் டாலர் லாபகரமான பதவியை விட்டுவிட்டு தனது சொந்த நிறுவனத்தைத் தொடங்குவதற்கான தனது அனுபவத்திலிருந்து நுண்ணறிவுகளைப் பகிர்ந்து கொள்கிறார்.',
  'zh-Hant':
    'Taro 的創始人兼首席執行官 Rahul Pandey 分享了他在 Meta 離開利潤豐厚的 80 萬美元職位創辦自己的公司的經歷。',
  id: 'Rahul Pandey, pendiri dan CEO Taro, berbagi wawasan dari pengalamannya meninggalkan posisi yang menguntungkan senilai $800 ribu di Meta untuk memulai perusahaannya sendiri.',
  pt: 'Rahul Pandey, fundador e CEO da Taro, compartilha insights de sua experiência ao deixar um cargo lucrativo de US$ 800 mil na Meta para abrir sua própria empresa.',
  nb: 'Rahul Pandey, grunnlegger og administrerende direktør i Taro, deler sine erfaringer med å forlate en lukrativ stilling på 800 000 dollar hos Meta for å starte sitt eget selskap.',
  nl: 'Rahul Pandey, de oprichter en CEO van Taro, deelt inzichten uit zijn ervaring met het verlaten van een lucratieve functie van $800K bij Meta om zijn eigen bedrijf te starten.',
  it: "Rahul Pandey, fondatore e CEO di Taro, condivide con noi l'esperienza di aver lasciato una posizione lucrativa da 800.000 dollari presso Meta per avviare la propria azienda.",
  fr: "Rahul Pandey, fondateur et PDG de Taro, nous fait part de son expérience lorsqu'il a quitté un poste lucratif de 800 000 dollars chez Meta pour créer sa propre entreprise.",
  de: 'Rahul Pandey, der Gründer und CEO von Taro, berichtet von seinen Erfahrungen, als er eine lukrative 800.000-Dollar-Stelle bei Meta verließ, um sein eigenes Unternehmen zu gründen.',
  ko: 'Taro의 창립자이자 CEO인 Rahul Pandey가 Meta에서 80만 달러의 연봉을 받던 직장을 그만두고 자신의 회사를 창업한 경험에서 얻은 인사이트를 공유합니다.',
  fi: 'Taron perustaja ja toimitusjohtaja Rahul Pandey kertoo kokemuksistaan, jotka hän sai jättäessään tuottoisan 800 000 dollarin työpaikan Metassa ja aloittaessaan oman yrityksen.',
  es: 'Rahul Pandey, fundador y consejero delegado de Taro, comparte su experiencia al dejar un lucrativo puesto de 800.000 dólares en Meta para crear su propia empresa.',
  sv: 'Rahul Pandey, grundare och VD för Taro, delar med sig av sina erfarenheter av att lämna en lukrativ tjänst på 800 000 USD på Meta för att starta sitt eget företag.',
  da: 'Rahul Pandey, grundlægger og CEO for Taro, deler ud af sine erfaringer med at forlade en lukrativ stilling til 800.000 dollars hos Meta for at starte sin egen virksomhed.',
  ja: 'タロ社の創業者でCEOのラフル・パンディが、メタ社での80万ドルの高収入の職を辞して起業した経験から得た洞察を語る。',
  ro: 'Rahul Pandey, fondatorul și directorul executiv al Taro, împărtășește informații din experiența sa de a părăsi un post profitabil de 800.000 de dolari la Meta pentru a-și înființa propria companie.',
  'zh-Hans':
    'Taro 公司的创始人兼首席执行官拉胡尔-潘迪（Rahul Pandey）分享了他从 Meta 公司价值 80 万美元的高薪职位离职后创办自己公司的心得体会。',
  hu: 'Rahul Pandey, a Taro alapítója és vezérigazgatója megosztja velünk tapasztalatait, amelyek abból adódtak, hogy elhagyott egy jövedelmező, 800 ezer dolláros állást a Metánál, és saját céget alapított.',
  cs: 'Rahul Pandey, zakladatel a generální ředitel společnosti Taro, se s vámi podělí o své zkušenosti s odchodem z lukrativní pozice ve společnosti Meta s 800 tisíci dolary a založením vlastní společnosti.',
  ru: 'Рахул Пандей, основатель и генеральный директор компании Taro, делится своими впечатлениями от опыта ухода с прибыльной должности в компании Meta, стоившей 800 тыс. долларов, и создания собственной компании.',
  el: 'Ο Rahul Pandey, ιδρυτής και διευθύνων σύμβουλος της Taro, μοιράζεται πληροφορίες από την εμπειρία του να εγκαταλείψει μια επικερδή θέση 800.000 δολαρίων στη Meta και να ξεκινήσει τη δική του εταιρεία.',
  sk: 'Rahul Pandey, zakladateľ a generálny riaditeľ spoločnosti Taro, sa delí o svoje skúsenosti z odchodu z lukratívnej pozície v spoločnosti Meta, ktorá stála 800-tisíc dolárov, aby si založil vlastnú spoločnosť.',
  pl: 'Rahul Pandey, założyciel i dyrektor generalny Taro, dzieli się spostrzeżeniami ze swojego doświadczenia związanego z opuszczeniem lukratywnego stanowiska w Meta za 800 tysięcy dolarów, aby założyć własną firmę.',
  tr: "Taro'nun kurucusu ve CEO'su Rahul Pandey, kendi şirketini kurmak için Meta'daki 800 bin dolarlık kazançlı bir pozisyondan ayrılma deneyiminden edindiği bilgileri paylaşıyor.",
}

const bulletTwo = {
  en: 'He discusses utilizing YouTube and LinkedIn as significant channels for growing his business, highlighting their effectiveness in outreach and marketing.',
  ar: 'يناقش استخدام YouTube و LinkedIn كقنوات مهمة لتنمية أعماله ، ويسلط الضوء على فعاليتها في التوعية والتسويق.',
  hi: 'वह अपने व्यवसाय को बढ़ाने के लिए महत्वपूर्ण चैनलों के रूप में YouTube और लिंक्डइन का उपयोग करने पर चर्चा करता है, आउटरीच और मार्केटिंग में उनकी प्रभावशीलता पर प्रकाश डालता है।',
  he: 'הוא מדבר על השימוש ביוטיוב ובלינקדאין כערוצים משמעותיים לצמיחת העסק שלו, ומדגיש את האפקטיביות שלהם בהסברה ובשיווק.',
  ta: 'யூடியூப் மற்றும் லிங்க்ட்இன் ஆகியவற்றை தனது வணிகத்தை வளர்ப்பதற்கான குறிப்பிடத்தக்க சேனல்களாகப் பயன்படுத்துவது குறித்து அவர் விவாதிக்கிறார், அவுட்ரீச் மற்றும் மார்க்கெட்டிங்கில் அவற்றின் செயல்திறனை எடுத்துக்காட்டுகிறார்.',
  bn: 'তিনি ইউটিউব এবং লিঙ্কডইনকে তার ব্যবসা বাড়ানোর জন্য গুরুত্বপূর্ণ চ্যানেল হিসাবে ব্যবহার করার বিষয়ে আলোচনা করেছেন, আউটরিচ এবং বিপণনে তাদের কার্যকারিতা তুলে ধরেছেন।',
  th: 'เขากล่าวถึงการใช้ YouTube และ LinkedIn เป็นช่องทางสําคัญในการขยายธุรกิจของเขาโดยเน้นถึงประสิทธิภาพในการเผยแพร่และการตลาด',
  ro: 'El vorbește despre utilizarea YouTube și LinkedIn ca fiind canale importante pentru dezvoltarea afacerii sale, subliniind eficiența acestora în ceea ce privește promovarea și marketingul.',
  pt: 'Ele fala sobre a utilização do YouTube e do LinkedIn como canais importantes para o crescimento de seus negócios, destacando sua eficácia em termos de alcance e marketing.',
  da: 'Han taler om at bruge YouTube og LinkedIn som vigtige kanaler til at udvide sin forretning og fremhæver deres effektivitet i opsøgende arbejde og markedsføring.',
  de: 'Er erörtert die Nutzung von YouTube und LinkedIn als wichtige Kanäle für das Wachstum seines Unternehmens und hebt deren Effektivität bei der Kontaktaufnahme und beim Marketing hervor.',
  tr: "YouTube ve LinkedIn'i işini büyütmek için önemli kanallar olarak kullanmayı tartışıyor ve bunların erişim ve pazarlamadaki etkinliğini vurguluyor.",
  'zh-Hant': '他討論了利用YouTube和LinkedIn作為發展業務的重要渠道，強調了它們在推廣和行銷方面的有效性。',
  sv: 'Han diskuterar användningen av YouTube och LinkedIn som viktiga kanaler för att utveckla sin verksamhet, och lyfter fram deras effektivitet när det gäller uppsökande verksamhet och marknadsföring.',
  es: 'Habla de la utilización de YouTube y LinkedIn como canales importantes para hacer crecer su negocio, destacando su eficacia en la divulgación y el marketing.',
  pl: 'Omawia wykorzystanie YouTube i LinkedIn jako ważnych kanałów rozwoju swojej firmy, podkreślając ich skuteczność w docieraniu do odbiorców i marketingu.',
  it: "Parla dell'utilizzo di YouTube e LinkedIn come canali significativi per la crescita della sua attività, sottolineando la loro efficacia nella diffusione e nel marketing.",
  ko: '그는 비즈니스 성장을 위한 중요한 채널로 YouTube와 LinkedIn을 활용하고 홍보 및 마케팅에 있어 그 효과를 강조합니다.',
  hu: 'Beszámol a YouTube és a LinkedIn mint a vállalkozásának növekedését szolgáló jelentős csatornákról, kiemelve ezek hatékonyságát a kapcsolatteremtésben és a marketingben.',
  id: 'Dia membahas pemanfaatan YouTube dan LinkedIn sebagai saluran penting untuk mengembangkan bisnisnya, menyoroti keefektifannya dalam penjangkauan dan pemasaran.',
  nl: 'Hij bespreekt het gebruik van YouTube en LinkedIn als belangrijke kanalen om zijn bedrijf te laten groeien en benadrukt hun effectiviteit in outreach en marketing.',
  nb: 'Han diskuterer bruken av YouTube og LinkedIn som viktige kanaler for å utvide virksomheten, og fremhever hvor effektive de er når det gjelder oppsøkende virksomhet og markedsføring.',
  cs: 'Hovoří o využívání služeb YouTube a LinkedIn jako významných kanálů pro rozvoj svého podnikání a zdůrazňuje jejich efektivitu při oslovování a marketingu.',
  ja: 'YouTubeとLinkedInの活用について、アウトリーチとマーケティングにおける有効性を強調しながら、ビジネスを成長させる重要なチャンネルであることを語っている。',
  'zh-Hans': '他谈到，YouTube 和 LinkedIn 是他发展业务的重要渠道，并强调了这两个渠道在推广和营销方面的有效性。',
  fr: "Il évoque l'utilisation de YouTube et de LinkedIn comme canaux importants pour le développement de son entreprise, en soulignant leur efficacité en matière de sensibilisation et de marketing.",
  fi: 'Hän puhuu YouTuben ja LinkedInin hyödyntämisestä merkittävinä kanavina liiketoimintansa kasvattamisessa ja korostaa niiden tehokkuutta yhteydenpidossa ja markkinoinnissa.',
  sk: 'Hovorí o využívaní služieb YouTube a LinkedIn ako významných kanálov na rozvoj svojho podnikania a zdôrazňuje ich účinnosť pri oslovovaní a marketingu.',
  el: 'Συζητά τη χρήση του YouTube και του LinkedIn ως σημαντικών καναλιών για την ανάπτυξη της επιχείρησής του, τονίζοντας την αποτελεσματικότητά τους στην προβολή και το μάρκετινγκ.',
  ru: 'Он рассказывает об использовании YouTube и LinkedIn в качестве важных каналов развития своего бизнеса, подчеркивая их эффективность в информационно-разъяснительной работе и маркетинге.',
}

const bulletThree = {
  en: 'Pandey reflects on the surprising challenges he faced transitioning from an engineer to a startup founder, offering a unique perspective on the entrepreneurial journey.',
  th: 'Pandey สะท้อนให้เห็นถึงความท้าทายที่น่าประหลาดใจที่เขาต้องเผชิญในการเปลี่ยนจากวิศวกรเป็นผู้ก่อตั้งสตาร์ทอัพโดยนําเสนอมุมมองที่ไม่เหมือนใครเกี่ยวกับเส้นทางการเป็นผู้ประกอบการ',
  ar: 'يتأمل باندي في التحديات المفاجئة التي واجهها في الانتقال من مهندس إلى مؤسس شركة ناشئة، ويقدم منظورا فريدا لرحلة ريادة الأعمال.',
  hi: 'पांडे ने एक इंजीनियर से स्टार्टअप संस्थापक बनने के लिए आश्चर्यजनक चुनौतियों का सामना किया, जो उद्यमशीलता की यात्रा पर एक अनूठा दृष्टिकोण प्रदान करता है।',
  he: 'פנדי מספר על האתגרים המפתיעים שעמדו בפניו במעבר ממהנדס למייסד סטארט-אפ, ומציע נקודת מבט ייחודית על המסע היזמי.',
  bn: 'পান্ডে একজন প্রকৌশলী থেকে স্টার্টআপ প্রতিষ্ঠাতা হয়ে ওঠার সময় যে বিস্ময়কর চ্যালেঞ্জগুলির মুখোমুখি হয়েছিলেন তা প্রতিফলিত করেছেন, উদ্যোক্তা যাত্রায় একটি অনন্য দৃষ্টিভঙ্গি উপস্থাপন করেছেন।',
  ta: 'ஒரு பொறியாளராக இருந்து ஸ்டார்ட்அப் நிறுவனராக மாறியதில் அவர் எதிர்கொண்ட ஆச்சரியமான சவால்களை பாண்டே பிரதிபலிக்கிறார், தொழில்முனைவோர் பயணத்தில் ஒரு தனித்துவமான கண்ணோட்டத்தை வழங்குகிறார்.',
  'zh-Hant': 'Pandey 回顧了他從工程師轉變為初創公司創始人所面臨的令人驚訝的挑戰，為創業之旅提供了獨特的視角。',
  tr: 'Pandey, bir mühendisten bir startup kurucusuna geçişte karşılaştığı şaşırtıcı zorlukları anlatıyor ve girişimcilik yolculuğuna benzersiz bir bakış açısı sunuyor.',
  cs: 'Pandey se zamýšlí nad překvapivými problémy, kterým čelil při přechodu z inženýra na zakladatele startupu, a nabízí jedinečný pohled na podnikatelskou cestu.',
  de: 'Pandey reflektiert über die überraschenden Herausforderungen, mit denen er auf dem Weg vom Ingenieur zum Startup-Gründer konfrontiert wurde, und bietet eine einzigartige Perspektive auf die unternehmerische Reise.',
  da: 'Pandey reflekterer over de overraskende udfordringer, han stod over for, da han gik fra at være ingeniør til at grundlægge en startup, og giver et unikt perspektiv på iværksætterrejsen.',
  ko: '판데이는 엔지니어에서 스타트업 창업자로 전환하면서 겪었던 놀라운 도전에 대해 이야기하며 창업 여정에 대한 독특한 관점을 제시합니다.',
  pt: 'Pandey reflete sobre os desafios surpreendentes que enfrentou na transição de engenheiro para fundador de uma startup, oferecendo uma perspectiva única sobre a jornada empresarial.',
  nl: 'Pandey vertelt over de verrassende uitdagingen waarmee hij werd geconfronteerd bij de overgang van een ingenieur naar een oprichter van een startup en biedt zo een uniek perspectief op het ondernemerschap.',
  sv: 'Pandey berättar om de överraskande utmaningar han ställdes inför när han gick från ingenjör till startup-grundare, och ger ett unikt perspektiv på entreprenörsresan.',
  'zh-Hans': '潘迪回顾了自己从工程师转型为初创企业创始人所面临的惊人挑战，以独特的视角讲述了创业历程。',
  nb: 'Pandey reflekterer over de overraskende utfordringene han møtte da han gikk fra å være ingeniør til å bli gründer, og gir et unikt perspektiv på gründerreisen.',
  es: 'Pandey reflexiona sobre los sorprendentes retos a los que se enfrentó al pasar de ingeniero a fundador de una startup, ofreciendo una perspectiva única del viaje empresarial.',
  fr: "M. Pandey revient sur les défis surprenants qu'il a dû relever pour passer du statut d'ingénieur à celui de fondateur d'une startup, offrant ainsi une perspective unique sur l'aventure entrepreneuriale.",
  ro: 'Pandey reflectează asupra provocărilor surprinzătoare cu care s-a confruntat în tranziția de la inginer la fondator de startup, oferind o perspectivă unică asupra călătoriei antreprenoriale.',
  it: 'Pandey riflette sulle sorprendenti sfide che ha affrontato nel passaggio da ingegnere a fondatore di startup, offrendo una prospettiva unica sul percorso imprenditoriale.',
  fi: 'Pandey pohtii yllättäviä haasteita, joita hän kohtasi siirtyessään insinööristä startup-yrityksen perustajaksi, ja tarjoaa ainutlaatuisen näkökulman yrittäjyyden tielle.',
  hu: 'Pandey a mérnökből startup-alapítóvá válás meglepő kihívásairól beszél, és egyedülálló nézőpontot kínál a vállalkozói útról.',
  id: 'Pandey merefleksikan tantangan mengejutkan yang dihadapinya saat bertransisi dari seorang insinyur menjadi pendiri startup, dan menawarkan perspektif unik tentang perjalanan kewirausahaan.',
  ja: 'パンデイは、エンジニアからスタートアップの創業者に転身する際に直面した驚くべき挑戦について振り返り、起業家としての旅についてユニークな視点を提供している。',
  ru: 'Пандей размышляет об удивительных проблемах, с которыми он столкнулся, пройдя путь от инженера до основателя стартапа, и предлагает уникальный взгляд на путь предпринимателя.',
  el: 'Ο Pandey αντανακλά τις εκπληκτικές προκλήσεις που αντιμετώπισε κατά τη μετάβασή του από μηχανικός σε ιδρυτή νεοφυούς επιχείρησης, προσφέροντας μια μοναδική προοπτική για το επιχειρηματικό ταξίδι.',
  sk: 'Pandey sa zamýšľa nad prekvapujúcimi výzvami, ktorým čelil pri prechode z inžiniera na zakladateľa startupu, a ponúka jedinečný pohľad na podnikateľskú cestu.',
  pl: 'Pandey zastanawia się nad zaskakującymi wyzwaniami, przed którymi stanął, przechodząc od inżyniera do założyciela startupu, oferując unikalną perspektywę na podróż przedsiębiorcy.',
}

export const storyAd = {
  day: '2023-11-23',
  ar: {
    title: title['ar'],
    originSummary: [bulletOne['ar'], bulletTwo['ar'], bulletThree['ar']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  bn: {
    title: title['bn'],
    originSummary: [bulletOne['bn'], bulletTwo['bn'], bulletThree['bn']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  cs: {
    title: title['cs'],
    originSummary: [bulletOne['cs'], bulletTwo['cs'], bulletThree['cs']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  da: {
    title: title['da'],
    originSummary: [bulletOne['da'], bulletTwo['da'], bulletThree['da']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  de: {
    title: title['de'],
    originSummary: [bulletOne['de'], bulletTwo['de'], bulletThree['de']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  el: {
    title: title['el'],
    originSummary: [bulletOne['el'], bulletTwo['el'], bulletThree['el']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  en: {
    title: title['en'],
    originSummary: [bulletOne['en'], bulletTwo['en'], bulletThree['en']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  es: {
    title: title['es'],
    originSummary: [bulletOne['es'], bulletTwo['es'], bulletThree['es']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  fi: {
    title: title['fi'],
    originSummary: [bulletOne['fi'], bulletTwo['fi'], bulletThree['fi']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  fr: {
    title: title['fr'],
    originSummary: [bulletOne['fr'], bulletTwo['fr'], bulletThree['fr']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  he: {
    title: title['he'],
    originSummary: [bulletOne['he'], bulletTwo['he'], bulletThree['he']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  hi: {
    title: title['hi'],
    originSummary: [bulletOne['hi'], bulletTwo['hi'], bulletThree['hi']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  hu: {
    title: title['hu'],
    originSummary: [bulletOne['hu'], bulletTwo['hu'], bulletThree['hu']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  id: {
    title: title['id'],
    originSummary: [bulletOne['id'], bulletTwo['id'], bulletThree['id']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  it: {
    title: title['it'],
    originSummary: [bulletOne['it'], bulletTwo['it'], bulletThree['it']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  ja: {
    title: title['ja'],
    originSummary: [bulletOne['ja'], bulletTwo['ja'], bulletThree['ja']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  ko: {
    title: title['ko'],
    originSummary: [bulletOne['ko'], bulletTwo['ko'], bulletThree['ko']],
    originLink: 'https://relate.kr/?ref=heimdall',
  },
  nl: {
    title: title['nl'],
    originSummary: [bulletOne['nl'], bulletTwo['nl'], bulletThree['nl']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  nb: {
    title: title['nb'],
    originSummary: [bulletOne['nb'], bulletTwo['nb'], bulletThree['nb']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  pl: {
    title: title['pl'],
    originSummary: [bulletOne['pl'], bulletTwo['pl'], bulletThree['pl']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  pt: {
    title: title['pt'],
    originSummary: [bulletOne['pt'], bulletTwo['pt'], bulletThree['pt']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  ro: {
    title: title['ro'],
    originSummary: [bulletOne['ro'], bulletTwo['ro'], bulletThree['ro']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  ru: {
    title: title['ru'],
    originSummary: [bulletOne['ru'], bulletTwo['ru'], bulletThree['ru']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  sk: {
    title: title['sk'],
    originSummary: [bulletOne['sk'], bulletTwo['sk'], bulletThree['sk']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  sv: {
    title: title['sv'],
    originSummary: [bulletOne['sv'], bulletTwo['sv'], bulletThree['sv']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  ta: {
    title: title['ta'],
    originSummary: [bulletOne['ta'], bulletTwo['ta'], bulletThree['ta']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  th: {
    title: title['th'],
    originSummary: [bulletOne['th'], bulletTwo['th'], bulletThree['th']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  tr: {
    title: title['tr'],
    originSummary: [bulletOne['tr'], bulletTwo['tr'], bulletThree['tr']],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  'zh-Hans': {
    title: title["'zh-Hans'"],
    originSummary: [bulletOne["'zh-Hans'"], bulletTwo["'zh-Hans'"], bulletThree["'zh-Hans'"]],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
  'zh-Hant': {
    title: title["'zh-Hant'"],
    originSummary: [bulletOne["'zh-Hant'"], bulletTwo["'zh-Hant'"], bulletThree["'zh-Hant'"]],
    originLink: 'https://youtu.be/fHRzHEwn5ac',
  },
}
