export const LOCAL_HEIMDALL = {
  ar: 'هيمدال',
  bn: 'Heimdall',
  cs: 'Heimdall',
  da: 'Heimdall',
  de: 'Heimdall',
  el: 'Heimdall',
  en: 'Heimdall',
  es: 'Heimdall',
  fi: 'Heimdall',
  fr: 'Heimdall',
  he: 'היימדאל',
  hi: 'Heimdall',
  hu: 'Heimdall',
  id: 'Heimdall',
  it: 'Heimdall',
  ja: 'ヘイムダル',
  ko: '헤임달',
  nb: 'Heimdall',
  nl: 'Heimdall',
  pl: 'Heimdall',
  pt: 'Heimdall',
  ro: 'Heimdall',
  ru: 'Heimdall',
  sk: 'Heimdall',
  sv: 'Heimdall',
  ta: 'Heimdall',
  th: 'ไฮม์ดัลล์',
  tr: 'Heimdall',
  'zh-Hans': '海姆达尔',
  'zh-Hant': '海姆達爾',
}

export const LOCAL_HACKERNEWS = {
  ar: 'أخبار القراصنة',
  bn: 'হ্যাকার নিউজ',
  cs: 'Hacker News',
  da: 'Hacker-nyheder',
  de: 'Hacker-Nachrichten',
  el: 'Hacker News',
  en: 'Hacker News',
  es: 'Noticias Hacker',
  fi: 'Hacker News',
  fr: 'Hacker News',
  he: 'חדשות Hacker',
  hi: 'हैकर समाचार',
  hu: 'Hacker News',
  id: 'Berita Peretas',
  it: 'Notizie Hacker',
  ja: 'ハッカーニュース',
  ko: '해커뉴스',
  nb: 'Hacker News',
  nl: 'Hacker Nieuws',
  pl: 'Hacker News',
  pt: 'Notícias Hacker',
  ro: 'Hacker News',
  ru: 'Hacker News',
  sk: 'Hacker News',
  sv: 'Hacker Nyheter',
  ta: 'ஹேக்கர் செய்திகள்',
  th: 'ข่าวแฮ็กเกอร์',
  tr: 'Hacker Haberleri',
  'zh-Hans': '黑客新闻',
  'zh-Hant': '駭客新聞',
}

export const LOCAL_HACKERNEWS_SUMMARY = {
  ar: 'ملخص أخبار القراصنة',
  bn: 'হ্যাকার নিউজ সারসংক্ষেপ',
  cs: 'Hacker News Shrnutí',
  da: 'Resumé af Hacker News',
  de: 'Hacker News Zusammenfassung',
  el: 'Περίληψη Hacker News',
  en: 'Hacker News Summary',
  es: 'Resumen de Hacker News',
  fi: 'Hacker News yhteenveto',
  fr: 'Résumé de Hacker News',
  he: 'סיכום חדשות Hacker',
  hi: 'हैकर समाचार सारांश',
  hu: 'Hacker News Összefoglaló',
  id: 'Ringkasan Berita Peretas',
  it: 'Riassunto di Hacker News',
  ja: 'ハッカーニュースまとめ',
  ko: '해커뉴스 요약',
  nb: 'Sammendrag av Hacker News',
  nl: 'Samenvatting Hacker News',
  pl: 'Podsumowanie Hacker News',
  pt: 'Resumo do Hacker News',
  ro: 'Rezumat Hacker News',
  ru: 'Сводка новостей Hacker News',
  sk: 'Hacker News Zhrnutie',
  sv: 'Sammanfattning av Hacker News',
  ta: 'ஹேக்கர் செய்தி சுருக்கம்',
  th: 'สรุปข่าวแฮ็กเกอร์',
  tr: 'Hacker Haber Özeti',
  'zh-Hans': '黑客新闻摘要',
  'zh-Hant': '駭客新聞摘要',
}

export const LOCAL_REACTIONS = {
  ar: 'ردود الفعل',
  bn: 'প্রতিক্রিয়া',
  cs: 'Reakce',
  da: 'Reaktioner',
  de: 'Reaktionen',
  el: 'Αντιδράσεις',
  en: 'Reactions',
  es: 'Reacciones',
  fi: 'Reaktiot',
  fr: 'Réactions',
  he: 'תגובות',
  hi: 'प्रतिक्रियाओं',
  hu: 'Reakciók',
  id: 'Reaksi',
  it: 'Reazioni',
  ja: '反応',
  ko: '반응',
  nb: 'Reaksjoner',
  nl: 'Reacties',
  pl: 'Reakcje',
  pt: 'Reações',
  ro: 'Reacții',
  ru: 'Реакции',
  sk: 'Reakcie',
  sv: 'Reaktioner',
  ta: 'எதிர்வினைகள்',
  th: 'ปฏิกิริยา',
  tr: 'Tepkiler',
  'zh-Hans': '反应',
  'zh-Hant': '反應',
}

export const LOCAL_SHARE = {
  ar: 'سهم',
  bn: 'অংশীদারি',
  cs: 'Sdílet',
  da: 'Del',
  de: 'Teilen Sie',
  el: 'Μοιραστείτε το',
  en: 'Share',
  es: 'Compartir',
  fi: 'Jaa',
  fr: 'Partager',
  he: 'לשתף',
  hi: 'हिस्सा',
  hu: 'Megosztás',
  id: 'Bagikan',
  it: 'Condividi',
  ja: 'シェア',
  ko: '공유',
  nb: 'Dele',
  nl: 'Deel',
  pl: 'Udział',
  pt: 'Compartilhar',
  ro: 'Share',
  ru: 'Поделиться',
  sk: 'Zdieľať',
  sv: 'Andel',
  ta: 'பங்கு',
  th: 'ใช้ร่วมกัน',
  tr: 'Paylaş',
  'zh-Hans': '分享',
  'zh-Hant': '共用',
}

export const LOCAL_SPONSOR = {
  ar: 'كفيل',
  bn: 'স্পন্সর',
  cs: 'Sponzor',
  da: 'Sponsor',
  de: 'Förderer',
  el: 'Χορηγός',
  en: 'Sponsor',
  es: 'Patrocinador',
  fi: 'Sponsori',
  fr: 'Parrainage',
  he: 'הספונסר',
  hi: 'प्रायोजक',
  hu: 'Szponzor',
  id: 'Sponsor',
  it: 'Sponsor',
  ja: 'スポンサー',
  ko: '스폰서',
  nb: 'Sponsor',
  nl: 'Sponsor',
  pl: 'Sponsor',
  pt: 'Patrocinador',
  ro: 'Sponsor',
  ru: 'Спонсор',
  sk: 'Sponzor',
  sv: 'Sponsor',
  ta: 'பெயர்த்தந்தை',
  th: 'ผู้สนับสนุน',
  tr: 'Sponsor',
  'zh-Hans': '赞助商',
  'zh-Hant': '贊助者',
}

export const LOCAL_FEEDBACK = {
  ar: 'ردود الفعل',
  bn: 'প্রতিপ্রদান',
  cs: 'Zpětná vazba',
  da: 'Feedback',
  de: 'Rückmeldung',
  el: 'Ανατροφοδότηση',
  en: 'Feedback',
  es: 'Comentarios',
  fi: 'Palaute',
  fr: "Retour d'information",
  he: 'משוב',
  hi: 'प्रतिपुष्टि',
  hu: 'Visszajelzés',
  id: 'Umpan balik',
  it: 'Feedback',
  ja: 'フィードバック',
  ko: '피드백',
  nb: 'Tilbakemelding',
  nl: 'Feedback',
  pl: 'Informacje zwrotne',
  pt: 'Feedback',
  ro: 'Feedback',
  ru: 'Обратная связь',
  sk: 'Spätná väzba',
  sv: 'Återkoppling',
  ta: 'பின்னூட்டம்',
  th: 'การตอบสนอง',
  tr: 'Geri bildirim',
  'zh-Hans': '反馈意见',
  'zh-Hant': '反饋',
}

export const LOCAL_ADVERTISE_FIRST = {
  ar: 'هذه النشرة الإخبارية لديها قراء يوميا من الآلاف من المطورين ، مع معدل فتح مثير للإعجاب يزيد عن 50٪.',
  bn: 'এই নিউজলেটারের হাজার হাজার ডেভেলপারদের দৈনিক পাঠক রয়েছে, যার চিত্তাকর্ষক উন্মুক্ত হার 50% এরও বেশি।',
  cs: 'Tento zpravodaj denně odebírají tisíce vývojářů, přičemž míra otevření činí více než 50 %.',
  da: 'Dette nyhedsbrev læses dagligt af tusindvis af udviklere og har en imponerende åbningsrate på over 50 %.',
  de: 'Dieser Newsletter wird täglich von Tausenden von Entwicklern gelesen und hat eine beeindruckende Öffnungsrate von über 50 %.',
  el: 'Αυτό το ενημερωτικό δελτίο διαβάζεται καθημερινά από χιλιάδες προγραμματιστές, με εντυπωσιακό ποσοστό ανοίγματος πάνω από 50%.',
  en: 'This newsletter has a daily readership of thousands of developers, with an impressive open rate of over 50%.',
  es: 'Este boletín tiene una audiencia diaria de miles de desarrolladores, con una impresionante tasa de apertura superior al 50%.',
  fi: 'Uutiskirjeen päivittäinen lukijakunta koostuu tuhansista kehittäjistä, ja sen avausprosentti on vaikuttava, yli 50 %.',
  fr: "Cette lettre d'information est lue quotidiennement par des milliers de développeurs, avec un taux d'ouverture impressionnant de plus de 50 %.",
  he: 'לניוזלטר זה קהל קוראים יומי של אלפי מפתחים, עם שיעור פתיחה מרשים של מעל 50%.',
  hi: 'इस न्यूज़लेटर में 50% से अधिक की प्रभावशाली खुली दर के साथ हजारों डेवलपर्स का दैनिक पाठक वर्ग है।',
  hu: 'Ez a hírlevél naponta több ezer fejlesztőt olvas, és a megnyitási aránya több mint 50%.',
  id: 'Buletin ini memiliki pembaca harian yang terdiri dari ribuan pengembang, dengan tingkat keterbukaan yang mengesankan, yaitu lebih dari 50%.',
  it: 'Questa newsletter ha un numero di lettori giornaliero di migliaia di sviluppatori, con un tasso di apertura impressionante, superiore al 50%.',
  ja: 'このニュースレターは毎日数千人の開発者を読者に持ち、その開封率は50％を超える。',
  ko: '이 뉴스레터는 매일 전세계 수천 명의 개발자가 읽고 있으며, 50%가 넘는 놀라운 열람률을 자랑합니다.',
  nb: 'Nyhetsbrevet leses daglig av tusenvis av utviklere og har en imponerende åpningsrate på over 50 %.',
  nl: 'Deze nieuwsbrief heeft een dagelijks lezerspubliek van duizenden ontwikkelaars, met een indrukwekkende open rate van meer dan 50%.',
  pl: 'Ten biuletyn jest codziennie czytany przez tysiące programistów, z imponującym wskaźnikiem otwarć wynoszącym ponad 50%.',
  pt: 'Esse boletim informativo tem um público diário de milhares de desenvolvedores, com uma taxa de abertura impressionante de mais de 50%.',
  ro: 'Acest buletin informativ este citit zilnic de mii de dezvoltatori, cu o rată de deschidere impresionantă de peste 50%.',
  ru: 'Ежедневная аудитория этой рассылки насчитывает тысячи разработчиков, а показатель открываемости составляет более 50%.',
  sk: 'Tento newsletter denne čítajú tisíce vývojárov s pôsobivou mierou otvorenia viac ako 50 %.',
  sv: 'Nyhetsbrevet läses dagligen av tusentals utvecklare och har en imponerande öppningsfrekvens på över 50 %.',
  ta: 'இந்த செய்திமடல் ஆயிரக்கணக்கான டெவலப்பர்களின் தினசரி வாசகர்களைக் கொண்டுள்ளது, இது 50% க்கும் அதிகமான திறந்த விகிதத்துடன்.',
  th: 'จดหมายข่าวนี้มีผู้อ่านรายวันของนักพัฒนาหลายพันคนโดยมีอัตราการเปิดที่น่าประทับใจมากกว่า 50%',
  tr: "Bu bültenin günlük binlerce geliştiriciden oluşan bir okuyucu kitlesi ve %50'nin üzerinde etkileyici bir açılma oranı vardır.",
  'zh-Hans': '这份时事通讯每天有数千名开发人员阅读，打开率超过 50%，令人印象深刻。',
  'zh-Hant': '該通訊每天有數千名開發人員的讀者群，打開率超過50%，令人印象深刻。',
}

export const LOCAL_ADVERTISE_SECOND = {
  ar: 'إذا كنت ترغب في الإعلان عن شركتك أو منتجك ، فلا تتردد في الاتصال بي.',
  bn: 'আপনি যদি আপনার কোম্পানী বা পণ্য বিজ্ঞাপন দিতে চান, আমার সাথে যোগাযোগ করতে দ্বিধা করবেন না।',
  cs: 'Pokud chcete propagovat svou společnost nebo produkt, neváhejte mě kontaktovat.',
  da: 'Hvis du vil reklamere for din virksomhed eller dit produkt, så tøv ikke med at kontakte mig.',
  de: 'Wenn Sie für Ihr Unternehmen oder Produkt werben möchten, zögern Sie nicht, mich zu kontaktieren.',
  el: 'Αν θέλετε να διαφημίσετε την εταιρεία ή το προϊόν σας, μη διστάσετε να επικοινωνήσετε μαζί μου.',
  en: "If you want to advertise your company or product, don't hesitate to contact me.",
  es: 'Si desea anunciar su empresa o producto, no dude en ponerse en contacto conmigo.',
  fi: 'Jos haluat mainostaa yritystäsi tai tuotteitasi, älä epäröi ottaa minuun yhteyttä.',
  fr: "Si vous souhaitez faire de la publicité pour votre entreprise ou votre produit, n'hésitez pas à me contacter.",
  he: 'אם אתה רוצה לפרסם את החברה או המוצר שלך, אל תהסס לפנות אלי.',
  hi: 'यदि आप अपनी कंपनी या उत्पाद का विज्ञापन करना चाहते हैं, तो मुझसे संपर्क करने में संकोच न करें।',
  hu: 'Ha reklámozni szeretné cégét vagy termékét, ne habozzon kapcsolatba lépni velem.',
  id: 'Jika Anda ingin mengiklankan perusahaan atau produk Anda, jangan ragu untuk menghubungi saya.',
  it: 'Se volete pubblicizzare la vostra azienda o il vostro prodotto, non esitate a contattarmi.',
  ja: 'あなたの会社や製品を宣伝したいのなら、遠慮なく私に連絡してください。',
  ko: '회사나 제품을 광고하고 싶으시다면 주저하지 마시고 연락주세요.',
  nb: 'Hvis du ønsker å annonsere for din bedrift eller ditt produkt, er du velkommen til å kontakte meg.',
  nl: 'Als je reclame wilt maken voor je bedrijf of product, aarzel dan niet om contact met me op te nemen.',
  pl: 'Jeśli chcesz zareklamować swoją firmę lub produkt, nie wahaj się ze mną skontaktować.',
  pt: 'Se quiser anunciar sua empresa ou produto, não hesite em entrar em contato comigo.',
  ro: 'Dacă doriți să vă faceți publicitate pentru compania sau produsul dumneavoastră, nu ezitați să mă contactați.',
  ru: 'Если Вы хотите прорекламировать свою компанию или продукт, не стесняйтесь обращаться ко мне.',
  sk: 'Ak chcete propagovať svoju spoločnosť alebo produkt, neváhajte ma kontaktovať.',
  sv: 'Om du vill marknadsföra ditt företag eller din produkt, tveka inte att kontakta mig.',
  ta: 'உங்கள் நிறுவனம் அல்லது தயாரிப்பை விளம்பரப்படுத்த விரும்பினால், என்னைத் தொடர்பு கொள்ள தயங்க வேண்டாம்.',
  th: 'หากคุณต้องการโฆษณา บริษัท หรือผลิตภัณฑ์ของคุณอย่าลังเลที่จะติดต่อฉัน',
  tr: 'Şirketinizin veya ürününüzün reklamını yapmak istiyorsanız, benimle iletişime geçmekten çekinmeyin.',
  'zh-Hans': '如果您想为您的公司或产品做广告，请随时与我联系。',
  'zh-Hant': '如果您想宣傳您的公司或產品，請隨時與我聯繫。',
}

export const LOCAL_CONTACT = {
  ar: '[الاتصال](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  bn: '[যোগাযোগ](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  cs: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  da: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  de: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  el: '[Επικοινωνία](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  en: '[Contact](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  es: '[Póngase en contacto con](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  fi: '[Ota yhteyttä](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  fr: '[Contact](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  he: '[איש קשר](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  hi: '[संपर्क](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  hu: '[Kapcsolat](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  id: '[Kontak](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  it: '[Contatto](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  ja: '[連絡先](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  ko: '[연락처](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  nb: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  nl: '[Neem contact op met](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  pl: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  pt: '[Contato](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  ro: '[Contactați](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  ru: '[Связаться с](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  sk: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  sv: '[Kontakt](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  ta: '[தொடுநிலை](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  th: '[ติดต่อ](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  tr: '[İletişim](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  'zh-Hans': '[联系方式](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
  'zh-Hant': '[聯繫](https://airtable.com/appLfbX7pNQxpBx00/shrfpPSEbLVSXz4r7@TrackLink)',
}

export const LOCAL_TODAYS_HN = {
  ar: 'ملخص أخبار القراصنة اليوم',
  bn: 'আজকের এইচএন সারসংক্ষেপ',
  cs: 'Dnešní shrnutí Hacker News',
  da: 'Dagens resumé af Hacker News',
  de: 'Die heutige Zusammenfassung der Hacker News',
  el: 'Η σημερινή περίληψη των Hacker News',
  en: "Today's Hacker News Summary",
  es: 'Resumen de Hacker News de hoy',
  fi: 'Tämän päivän Hacker News -yhteenveto',
  fr: "Résumé des Hacker News d'aujourd'hui",
  he: 'סיכום חדשות ההאקרים של היום',
  hi: 'आज का हैकर समाचार सारांश',
  hu: 'A mai Hacker News összefoglalója',
  id: 'Ringkasan Berita Peretas Hari Ini',
  it: 'Riassunto delle notizie Hacker di oggi',
  ja: '本日のハッカーニュースまとめ',
  ko: '오늘의 해커뉴스 요약',
  nb: 'Sammendrag av dagens Hacker News',
  nl: 'Hacker News samenvatting van vandaag',
  pl: 'Dzisiejsze podsumowanie Hacker News',
  pt: 'Resumo do Hacker News de hoje',
  ro: 'Rezumatul Hacker News de astăzi',
  ru: 'Сегодняшняя сводка новостей Hacker News',
  sk: 'Dnešné zhrnutie Hacker News',
  sv: 'Sammanfattning av dagens Hacker News',
  ta: 'இன்றைய HN சுருக்கம்',
  th: 'สรุปข่าวแฮ็กเกอร์วันนี้',
  tr: 'Bugünün Hacker Haber Özeti',
  'zh-Hans': '今日黑客新闻摘要',
  'zh-Hant': '今日駭客新聞摘要',
}
