export const LOCAL_REACTIONS = {
  en: 'Reactions',
  he: 'תגובות',
  hi: 'प्रतिक्रियाओं',
  ar: 'ردود الفعل',
  th: 'ปฏิกิริยา',
  zu: 'Ukusabela',
  'zh-Hant': '反應',
  id: 'Reaksi',
  sk: 'Reakcie',
  da: 'Reaktioner',
  fr: 'Réactions',
  nb: 'Reaksjoner',
  de: 'Reaktionen',
  it: 'Reazioni',
  fi: 'Reaktiot',
  es: 'Reacciones',
  el: 'Αντιδράσεις',
  ja: '反応',
  pl: 'Reakcje',
  cs: 'Reakce',
  ko: '반응',
  nl: 'Reacties',
  ro: 'Reacții',
  hu: 'Reakciók',
  'zh-Hans': '反应',
  tr: 'Tepkiler',
  ru: 'Реакции',
  pt: 'Reações',
  sv: 'Reaktioner',
}

export const LOCAL_SHARE = {
  en: 'Share',
  'zh-Hant': '共用',
  ar: 'سهم',
  hi: 'हिस्सा',
  bn: 'অংশীদারি',
  he: 'לשתף',
  ta: 'பங்கு',
  th: 'ใช้ร่วมกัน',
  da: 'Del',
  it: 'Condividi',
  id: 'Bagikan',
  fr: 'Partager',
  ko: '공유',
  ja: 'シェア',
  de: 'Teilen Sie',
  hu: 'Megosztás',
  cs: 'Sdílet',
  sv: 'Andel',
  fi: 'Jaa',
  sk: 'Zdieľať',
  pt: 'Compartilhar',
  es: 'Compartir',
  'zh-Hans': '分享',
  nb: 'Dele',
  nl: 'Deel',
  pl: 'Udział',
  el: 'Μοιραστείτε το',
  ro: 'Share',
  ru: 'Поделиться',
  tr: 'Paylaş',
}

export const LOCAL_SPONSOR = {
  en: 'Sponsor',
  ar: 'كفيل',
  hi: 'प्रायोजक',
  he: 'הספונסר',
  th: 'ผู้สนับสนุน',
  bn: 'স্পন্সর',
  ta: 'பெயர்த்தந்தை',
  'zh-Hant': '贊助者',
  it: 'Sponsor',
  sv: 'Sponsor',
  es: 'Patrocinador',
  nl: 'Sponsor',
  fr: 'Parrainage',
  id: 'Sponsor',
  fi: 'Sponsori',
  da: 'Sponsor',
  nb: 'Sponsor',
  hu: 'Szponzor',
  'zh-Hans': '赞助商',
  sk: 'Sponzor',
  pl: 'Sponsor',
  de: 'Förderer',
  tr: 'Sponsor',
  ko: '스폰서',
  ja: 'スポンサー',
  el: 'Χορηγός',
  ru: 'Спонсор',
  cs: 'Sponzor',
  pt: 'Patrocinador',
  ro: 'Sponsor',
}

export const LOCAL_FEEDBACK = {
  en: 'Feedback',
  ar: 'ردود الفعل',
  'zh-Hant': '反饋',
  hi: 'प्रतिपुष्टि',
  bn: 'প্রতিপ্রদান',
  he: 'משוב',
  th: 'การตอบสนอง',
  ta: 'பின்னூட்டம்',
  pl: 'Informacje zwrotne',
  fr: "Retour d'information",
  sk: 'Spätná väzba',
  sv: 'Återkoppling',
  'zh-Hans': '反馈意见',
  ru: 'Обратная связь',
  pt: 'Feedback',
  ko: '피드백',
  ja: 'フィードバック',
  es: 'Comentarios',
  da: 'Feedback',
  it: 'Feedback',
  de: 'Rückmeldung',
  hu: 'Visszajelzés',
  el: 'Ανατροφοδότηση',
  fi: 'Palaute',
  ro: 'Feedback',
  nl: 'Feedback',
  id: 'Umpan balik',
  tr: 'Geri bildirim',
  nb: 'Tilbakemelding',
  cs: 'Zpětná vazba',
}

export const LOCAL_ADVERTISE_FIRST = {
  en: 'This newsletter has a daily readership of thousands of developers, with an impressive open rate of over 50%.',
  th: 'จดหมายข่าวนี้มีผู้อ่านรายวันของนักพัฒนาหลายพันคนโดยมีอัตราการเปิดที่น่าประทับใจมากกว่า 50%',
  bn: 'এই নিউজলেটারের হাজার হাজার ডেভেলপারদের দৈনিক পাঠক রয়েছে, যার চিত্তাকর্ষক উন্মুক্ত হার 50% এরও বেশি।',
  ar: 'هذه النشرة الإخبارية لديها قراء يوميا من الآلاف من المطورين ، مع معدل فتح مثير للإعجاب يزيد عن 50٪.',
  hi: 'इस न्यूज़लेटर में 50% से अधिक की प्रभावशाली खुली दर के साथ हजारों डेवलपर्स का दैनिक पाठक वर्ग है।',
  ta: 'இந்த செய்திமடல் ஆயிரக்கணக்கான டெவலப்பர்களின் தினசரி வாசகர்களைக் கொண்டுள்ளது, இது 50% க்கும் அதிகமான திறந்த விகிதத்துடன்.',
  he: 'לניוזלטר זה קהל קוראים יומי של אלפי מפתחים, עם שיעור פתיחה מרשים של מעל 50%.',
  'zh-Hant': '該通訊每天有數千名開發人員的讀者群，打開率超過50%，令人印象深刻。',
  sk: 'Tento newsletter denne čítajú tisíce vývojárov s pôsobivou mierou otvorenia viac ako 50 %.',
  ru: 'Ежедневная аудитория этой рассылки насчитывает тысячи разработчиков, а показатель открываемости составляет более 50%.',
  sv: 'Nyhetsbrevet läses dagligen av tusentals utvecklare och har en imponerande öppningsfrekvens på över 50 %.',
  pl: 'Ten biuletyn jest codziennie czytany przez tysiące programistów, z imponującym wskaźnikiem otwarć wynoszącym ponad 50%.',
  ro: 'Acest buletin informativ este citit zilnic de mii de dezvoltatori, cu o rată de deschidere impresionantă de peste 50%.',
  fr: "Cette lettre d'information est lue quotidiennement par des milliers de développeurs, avec un taux d'ouverture impressionnant de plus de 50 %.",
  es: 'Este boletín tiene una audiencia diaria de miles de desarrolladores, con una impresionante tasa de apertura superior al 50%.',
  cs: 'Tento zpravodaj denně odebírají tisíce vývojářů, přičemž míra otevření činí více než 50 %.',
  hu: 'Ez a hírlevél naponta több ezer fejlesztőt olvas, és a megnyitási aránya több mint 50%.',
  de: 'Dieser Newsletter wird täglich von Tausenden von Entwicklern gelesen und hat eine beeindruckende Öffnungsrate von über 50 %.',
  pt: 'Esse boletim informativo tem um público diário de milhares de desenvolvedores, com uma taxa de abertura impressionante de mais de 50%.',
  nl: 'Deze nieuwsbrief heeft een dagelijks lezerspubliek van duizenden ontwikkelaars, met een indrukwekkende open rate van meer dan 50%.',
  ko: '이 뉴스레터는 매일 전세계 수천 명의 개발자가 읽고 있으며, 50%가 넘는 놀라운 열람률을 자랑합니다.',
  'zh-Hans': '这份时事通讯每天有数千名开发人员阅读，打开率超过 50%，令人印象深刻。',
  da: 'Dette nyhedsbrev læses dagligt af tusindvis af udviklere og har en imponerende åbningsrate på over 50 %.',
  el: 'Αυτό το ενημερωτικό δελτίο διαβάζεται καθημερινά από χιλιάδες προγραμματιστές, με εντυπωσιακό ποσοστό ανοίγματος πάνω από 50%.',
  id: 'Buletin ini memiliki pembaca harian yang terdiri dari ribuan pengembang, dengan tingkat keterbukaan yang mengesankan, yaitu lebih dari 50%.',
  it: 'Questa newsletter ha un numero di lettori giornaliero di migliaia di sviluppatori, con un tasso di apertura impressionante, superiore al 50%.',
  ja: 'このニュースレターは毎日数千人の開発者を読者に持ち、その開封率は50％を超える。',
  tr: "Bu bültenin günlük binlerce geliştiriciden oluşan bir okuyucu kitlesi ve %50'nin üzerinde etkileyici bir açılma oranı vardır.",
  fi: 'Uutiskirjeen päivittäinen lukijakunta koostuu tuhansista kehittäjistä, ja sen avausprosentti on vaikuttava, yli 50 %.',
  nb: 'Nyhetsbrevet leses daglig av tusenvis av utviklere og har en imponerende åpningsrate på over 50 %.',
}

export const LOCAL_ADVERTISE_SECOND = {
  en: "If you want to advertise your company or product, don't hesitate to contact me.",
  th: 'หากคุณต้องการโฆษณา บริษัท หรือผลิตภัณฑ์ของคุณอย่าลังเลที่จะติดต่อฉัน',
  ar: 'إذا كنت ترغب في الإعلان عن شركتك أو منتجك ، فلا تتردد في الاتصال بي.',
  hi: 'यदि आप अपनी कंपनी या उत्पाद का विज्ञापन करना चाहते हैं, तो मुझसे संपर्क करने में संकोच न करें।',
  he: 'אם אתה רוצה לפרסם את החברה או המוצר שלך, אל תהסס לפנות אלי.',
  'zh-Hant': '如果您想宣傳您的公司或產品，請隨時與我聯繫。',
  ta: 'உங்கள் நிறுவனம் அல்லது தயாரிப்பை விளம்பரப்படுத்த விரும்பினால், என்னைத் தொடர்பு கொள்ள தயங்க வேண்டாம்.',
  ja: 'あなたの会社や製品を宣伝したいのなら、遠慮なく私に連絡してください。',
  cs: 'Pokud chcete propagovat svou společnost nebo produkt, neváhejte mě kontaktovat.',
  fr: "Si vous souhaitez faire de la publicité pour votre entreprise ou votre produit, n'hésitez pas à me contacter.",
  pt: 'Se quiser anunciar sua empresa ou produto, não hesite em entrar em contato comigo.',
  'zh-Hans': '如果您想为您的公司或产品做广告，请随时与我联系。',
  sv: 'Om du vill marknadsföra ditt företag eller din produkt, tveka inte att kontakta mig.',
  pl: 'Jeśli chcesz zareklamować swoją firmę lub produkt, nie wahaj się ze mną skontaktować.',
  ru: 'Если Вы хотите прорекламировать свою компанию или продукт, не стесняйтесь обращаться ко мне.',
  nb: 'Hvis du ønsker å annonsere for din bedrift eller ditt produkt, er du velkommen til å kontakte meg.',
  es: 'Si desea anunciar su empresa o producto, no dude en ponerse en contacto conmigo.',
  it: 'Se volete pubblicizzare la vostra azienda o il vostro prodotto, non esitate a contattarmi.',
  hu: 'Ha reklámozni szeretné cégét vagy termékét, ne habozzon kapcsolatba lépni velem.',
  sk: 'Ak chcete propagovať svoju spoločnosť alebo produkt, neváhajte ma kontaktovať.',
  nl: 'Als je reclame wilt maken voor je bedrijf of product, aarzel dan niet om contact met me op te nemen.',
  id: 'Jika Anda ingin mengiklankan perusahaan atau produk Anda, jangan ragu untuk menghubungi saya.',
  ko: '회사나 제품을 광고하고 싶으시다면 주저하지 마시고 연락주세요.',
  fi: 'Jos haluat mainostaa yritystäsi tai tuotteitasi, älä epäröi ottaa minuun yhteyttä.',
  tr: 'Şirketinizin veya ürününüzün reklamını yapmak istiyorsanız, benimle iletişime geçmekten çekinmeyin.',
  de: 'Wenn Sie für Ihr Unternehmen oder Produkt werben möchten, zögern Sie nicht, mich zu kontaktieren.',
  el: 'Αν θέλετε να διαφημίσετε την εταιρεία ή το προϊόν σας, μη διστάσετε να επικοινωνήσετε μαζί μου.',
  da: 'Hvis du vil reklamere for din virksomhed eller dit produkt, så tøv ikke med at kontakte mig.',
  ro: 'Dacă doriți să vă faceți publicitate pentru compania sau produsul dumneavoastră, nu ezitați să mă contactați.',
  bn: 'আপনি যদি আপনার কোম্পানী বা পণ্য বিজ্ঞাপন দিতে চান, আমার সাথে যোগাযোগ করতে দ্বিধা করবেন না।',
}

export const LOCAL_CONTACT = {
  en: '[Contact](https://mailhide.io/en/e/IXndXpED)',
  ta: '[தொடுநிலை](https://mailhide.io/en/e/IXndXpED)',
  bn: '[যোগাযোগ](https://mailhide.io/en/e/IXndXpED)',
  ar: '[الاتصال](https://mailhide.io/en/e/IXndXpED)',
  hi: '[संपर्क](https://mailhide.io/en/e/IXndXpED)',
  he: '[איש קשר](https://mailhide.io/en/e/IXndXpED)',
  'zh-Hant': '[聯繫](https://mailhide.io/en/e/IXndXpED)',
  th: '[ติดต่อ](https://mailhide.io/en/e/IXndXpED)',
  fr: '[Contact](https://mailhide.io/en/e/IXndXpED)',
  el: '[Επικοινωνία](https://mailhide.io/en/e/IXndXpED)',
  de: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  id: '[Kontak](https://mailhide.io/en/e/IXndXpED)',
  es: '[Póngase en contacto con](https://mailhide.io/en/e/IXndXpED)',
  fi: '[Ota yhteyttä](https://mailhide.io/en/e/IXndXpED)',
  da: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  nb: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  'zh-Hans': '[联系方式](https://mailhide.io/en/e/IXndXpED)',
  pt: '[Contato](https://mailhide.io/en/e/IXndXpED)',
  sv: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  ru: '[Связаться с](https://mailhide.io/en/e/IXndXpED)',
  it: '[Contatto](https://mailhide.io/en/e/IXndXpED)',
  pl: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  cs: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  hu: '[Kapcsolat](https://mailhide.io/en/e/IXndXpED)',
  sk: '[Kontakt](https://mailhide.io/en/e/IXndXpED)',
  ja: '[連絡先](https://mailhide.io/en/e/IXndXpED)',
  tr: '[İletişim](https://mailhide.io/en/e/IXndXpED)',
  ko: '[연락처](https://mailhide.io/en/e/IXndXpED)',
  nl: '[Neem contact op met](https://mailhide.io/en/e/IXndXpED)',
  ro: '[Contactați](https://mailhide.io/en/e/IXndXpED)',
}
