export const LinguineConfig = {
  af: { name: 'Afrikaans', provider: 'BING' },
  ak: { name: 'Twi (Akan)', provider: 'GOOGLE' },
  am: { name: 'Amharic', provider: 'BING' },
  ar: { name: 'Arabic', provider: 'BING' },
  as: { name: 'Assamese', provider: 'BING' },
  ay: { name: 'Aymara', provider: 'GOOGLE' },
  az: { name: 'Azerbaijani', provider: 'BING' },
  ba: { name: 'Bashkir', provider: 'BING' },
  be: { name: 'Belarusian', provider: 'GOOGLE' },
  bg: { name: 'Bulgarian', provider: 'DEEPL' },
  bho: { name: 'Bhojpuri', provider: 'GOOGLE' },
  bm: { name: 'Bambara', provider: 'GOOGLE' },
  bn: { name: 'Bengali', provider: 'BING' },
  bo: { name: 'Tibetan', provider: 'BING' },
  bs: { name: 'Bosnian', provider: 'BING' },
  ca: { name: 'Catalan', provider: 'BING' },
  ceb: { name: 'Cebuano', provider: 'GOOGLE' },
  ckb: { name: 'Kurdish (Sorani)', provider: 'GOOGLE' },
  co: { name: 'Corsican', provider: 'GOOGLE' },
  cs: { name: 'Czech', provider: 'DEEPL' },
  cy: { name: 'Welsh', provider: 'BING' },
  da: { name: 'Danish', provider: 'DEEPL' },
  de: { name: 'German', provider: 'DEEPL' },
  doi: { name: 'Dogri', provider: 'GOOGLE' },
  dv: { name: 'Dhivehi', provider: 'BING' },
  ee: { name: 'Ewe', provider: 'GOOGLE' },
  el: { name: 'Greek', provider: 'DEEPL' },
  en: { name: 'English', provider: 'DEEPL' },
  eo: { name: 'Esperanto', provider: 'GOOGLE' },
  es: { name: 'Spanish', provider: 'DEEPL' },
  et: { name: 'Estonian', provider: 'DEEPL' },
  eu: { name: 'Basque', provider: 'BING' },
  fa: { name: 'Persian', provider: 'BING' },
  fi: { name: 'Finnish', provider: 'DEEPL' },
  fil: { name: 'Filipino (Tagalog)', provider: 'BING' },
  fj: { name: 'Fijian', provider: 'BING' },
  fo: { name: 'Faroese', provider: 'BING' },
  fr: { name: 'French', provider: 'DEEPL' },
  fy: { name: 'Frisian', provider: 'GOOGLE' },
  ga: { name: 'Irish', provider: 'BING' },
  gd: { name: 'Scots Gaelic', provider: 'GOOGLE' },
  gl: { name: 'Galician', provider: 'BING' },
  gn: { name: 'Guarani', provider: 'GOOGLE' },
  gom: { name: 'Konkani', provider: 'GOOGLE' },
  gu: { name: 'Gujarati', provider: 'BING' },
  ha: { name: 'Hausa', provider: 'GOOGLE' },
  haw: { name: 'Hawaiian', provider: 'GOOGLE' },
  he: { name: 'Hebrew', provider: 'BING' },
  hi: { name: 'Hindi', provider: 'BING' },
  hmn: { name: 'Hmong', provider: 'GOOGLE' },
  hr: { name: 'Croatian', provider: 'BING' },
  hsb: { name: 'Upper Sorbian', provider: 'BING' },
  ht: { name: 'Haitian Creole', provider: 'BING' },
  hu: { name: 'Hungarian', provider: 'DEEPL' },
  hy: { name: 'Armenian', provider: 'BING' },
  id: { name: 'Indonesian', provider: 'DEEPL' },
  ig: { name: 'Igbo', provider: 'GOOGLE' },
  ikt: { name: 'Inuinnaqtun', provider: 'BING' },
  ilo: { name: 'Ilocano', provider: 'GOOGLE' },
  is: { name: 'Icelandic', provider: 'BING' },
  it: { name: 'Italian', provider: 'DEEPL' },
  iu: { name: 'Inuktitut', provider: 'BING' },
  ja: { name: 'Japanese', provider: 'DEEPL' },
  jv: { name: 'Javanese', provider: 'GOOGLE' },
  ka: { name: 'Georgian', provider: 'GOOGLE' },
  kk: { name: 'Kazakh', provider: 'BING' },
  km: { name: 'Khmer', provider: 'BING' },
  kmr: { name: 'Kurdish (Northern)', provider: 'BING' },
  kn: { name: 'Kannada', provider: 'BING' },
  ko: { name: 'Korean', provider: 'DEEPL' },
  kri: { name: 'Krio', provider: 'GOOGLE' },
  ku: { name: 'Kurdish', provider: 'BING' },
  ky: { name: 'Kyrgyz', provider: 'BING' },
  la: { name: 'Latin', provider: 'GOOGLE' },
  lb: { name: 'Luxembourgish', provider: 'GOOGLE' },
  lg: { name: 'Luganda', provider: 'GOOGLE' },
  ln: { name: 'Lingala', provider: 'GOOGLE' },
  lo: { name: 'Lao', provider: 'BING' },
  lt: { name: 'Lithuanian', provider: 'DEEPL' },
  lus: { name: 'Mizo', provider: 'GOOGLE' },
  lv: { name: 'Latvian', provider: 'DEEPL' },
  mai: { name: 'Maithili', provider: 'GOOGLE' },
  mg: { name: 'Malagasy', provider: 'BING' },
  mi: { name: 'Maori', provider: 'BING' },
  mk: { name: 'Macedonian', provider: 'BING' },
  ml: { name: 'Malayalam', provider: 'BING' },
  mn: { name: 'Mongolian', provider: 'BING' },
  mni: { name: 'Meiteilon (Manipuri)', provider: 'GOOGLE' },
  mr: { name: 'Marathi', provider: 'BING' },
  ms: { name: 'Malay', provider: 'BING' },
  mt: { name: 'Maltese', provider: 'BING' },
  mww: { name: 'Hmong Daw', provider: 'BING' },
  my: { name: 'Myanmar (Burmese)', provider: 'BING' },
  ne: { name: 'Nepali', provider: 'BING' },
  nl: { name: 'Dutch', provider: 'DEEPL' },
  nb: { name: 'Norwegian', provider: 'DEEPL' },
  nso: { name: 'Sepedi', provider: 'GOOGLE' },
  ny: { name: 'Nyanja (Chichewa)', provider: 'GOOGLE' },
  om: { name: 'Oromo', provider: 'GOOGLE' },
  or: { name: 'Odia (Oriya)', provider: 'BING' },
  otq: { name: 'Queretaro Otomi', provider: 'BING' },
  pa: { name: 'Punjabi', provider: 'BING' },
  pl: { name: 'Polish', provider: 'DEEPL' },
  prs: { name: 'Dari', provider: 'BING' },
  ps: { name: 'Pashto', provider: 'BING' },
  pt: { name: 'Portuguese (Portugal, Brazil)', provider: 'DEEPL' },
  qu: { name: 'Quechua', provider: 'GOOGLE' },
  ro: { name: 'Romanian', provider: 'DEEPL' },
  ru: { name: 'Russian', provider: 'DEEPL' },
  rw: { name: 'Kinyarwanda', provider: 'GOOGLE' },
  sa: { name: 'Sanskrit', provider: 'GOOGLE' },
  sd: { name: 'Sindhi', provider: 'GOOGLE' },
  si: { name: 'Sinhala (Sinhalese)', provider: 'GOOGLE' },
  sk: { name: 'Slovak', provider: 'DEEPL' },
  sl: { name: 'Slovenian', provider: 'DEEPL' },
  sm: { name: 'Samoan', provider: 'BING' },
  sn: { name: 'Shona', provider: 'GOOGLE' },
  so: { name: 'Somali', provider: 'BING' },
  sq: { name: 'Albanian', provider: 'BING' },
  sr: { name: 'Serbian', provider: 'BING' },
  st: { name: 'Sesotho', provider: 'GOOGLE' },
  su: { name: 'Sundanese', provider: 'GOOGLE' },
  sv: { name: 'Swedish', provider: 'DEEPL' },
  sw: { name: 'Swahili', provider: 'BING' },
  ta: { name: 'Tamil', provider: 'BING' },
  te: { name: 'Telugu', provider: 'BING' },
  tg: { name: 'Tajik', provider: 'GOOGLE' },
  th: { name: 'Thai', provider: 'BING' },
  ti: { name: 'Tigrinya', provider: 'BING' },
  tk: { name: 'Turkmen', provider: 'BING' },
  tl: { name: 'Tagalog (Filipino)', provider: 'GOOGLE' },
  to: { name: 'Tongan', provider: 'BING' },
  tr: { name: 'Turkish', provider: 'DEEPL' },
  ts: { name: 'Tsonga', provider: 'GOOGLE' },
  tt: { name: 'Tatar', provider: 'BING' },
  ty: { name: 'Tahitian', provider: 'BING' },
  ug: { name: 'Uyghur', provider: 'BING' },
  uk: { name: 'Ukrainian', provider: 'DEEPL' },
  ur: { name: 'Urdu', provider: 'BING' },
  uz: { name: 'Uzbek', provider: 'BING' },
  vi: { name: 'Vietnamese', provider: 'BING' },
  xh: { name: 'Xhosa', provider: 'GOOGLE' },
  yi: { name: 'Yiddish', provider: 'GOOGLE' },
  yo: { name: 'Yoruba', provider: 'GOOGLE' },
  yua: { name: 'Yucatec Maya', provider: 'BING' },
  yue: { name: 'Cantonese (Traditional)', provider: 'BING' },
  'zh-CN': { name: 'Chinese (Simplified)', provider: 'DEEPL' },
  'zh-TW': { name: 'Chinese (Traditional)', provider: 'BING' },
  zu: { name: 'Zulu', provider: 'BING' },
}
