export const LinguineCore = {
  ko: { name: 'Korean', native: '한국어' },
  ar: { name: 'Arabic', native: 'العربية' },
  bn: { name: 'Bengali', native: 'বাংলা' },
  cs: { name: 'Czech', native: 'čeština' },
  da: { name: 'Danish', native: 'dansk' },
  de: { name: 'German', native: 'Deutsch' },
  el: { name: 'Greek', native: 'Ελληνικά' },
  en: { name: 'English', native: 'English' },
  es: { name: 'Spanish', native: 'español' },
  fi: { name: 'Finnish', native: 'suomi' },
  fr: { name: 'French', native: 'français' },
  he: { name: 'Hebrew', native: 'עברית' },
  hi: { name: 'Hindi', native: 'हिंदी' },
  hu: { name: 'Hungarian', native: 'magyar' },
  id: { name: 'Indonesian', native: 'Bahasa Indonesia' },
  it: { name: 'Italian', native: 'italiano' },
  ja: { name: 'Japanese', native: '日本語' },
  nb: { name: 'Norwegian', native: 'Norsk Bokmål' },
  nl: { name: 'Dutch', native: 'Nederlands' },
  pl: { name: 'Polish', native: 'polski' },
  pt: { name: 'Portuguese', native: 'português' },
  ro: { name: 'Romanian', native: 'română' },
  ru: { name: 'Russian', native: 'русский' },
  sk: { name: 'Slovak', native: 'slovenčina' },
  sv: { name: 'Swedish', native: 'svenska' },
  ta: { name: 'Tamil', native: 'தமிழ்' },
  th: { name: 'Thai', native: 'ไทย' },
  tr: { name: 'Turkish', native: 'Türkçe' },
  'zh-Hans': {
    name: 'Chinese Simplified',
    native: '中文 (简体中文)',
  },
  'zh-Hant': {
    name: 'Chinese Traditional',
    native: '中文 (繁體)',
  },
  vi: { name: 'Vietnamese', native: 'Tiếng Việt' },
}

export const LinguineList = Object.keys(LinguineCore)
