export const subscriptions = [
  // {
  //   query: 'AI',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'kimkj@usc.edu',
  // },
  // {
  //   query: 'AI',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'anaclumos@gmail.com',
  // },
  // {
  //   query: 'Tech Companies',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'kimkj@usc.edu',
  // },
  // {
  //   query: 'Tech Companies',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'anaclumos@gmail.com',
  // },
  // {
  //   query: 'junhoyeo',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'i@junho.io',
  // },
  // {
  //   query: 'Pinduoduo',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: 'Pinduoduo',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'anaclumos@gmail.com',
  // },
  // {
  //   query: '拼多多',
  //   serachResultLang: 'zh',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: '拼多多',
  //   serachResultLang: 'zh',
  //   locale: 'ko',
  //   email: 'anaclumos@gmail.com',
  // },
  // {
  //   query: 'TEMU marketplace',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: 'TEMU marketplace',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'anaclumos@gmail.com',
  // },
  {
    query: '스타트업',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '시스템반도체',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'youjin.ahn@gwanakanalog.com',
  },
  {
    query: '시스템반도체',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'Generative AI',
    serachResultLang: 'en',
    locale: 'en',
    email: 'jungwoolee0419@gmail.com',
  },
  {
    query: 'Generative AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'jungwoolee0419@gmail.com',
  },
  {
    query: 'Generative AI',
    serachResultLang: 'en',
    locale: 'en',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'Generative AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'Second Hand Marketplace',
    serachResultLang: 'en',
    locale: 'en',
    email: 'jaewha@gmail.com',
  },
  {
    query: 'Second Hand Marketplace',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'jaewha@gmail.com',
  },
  {
    query: 'Second Hand Marketplace',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '중고거래',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'jaewha@gmail.com',
  },
  {
    query: '중고거래',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '시황',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '시황',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'sunjaeianchoi@gmail.com',
  },
  {
    query: '친환경',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: '친환경',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '포장재',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: '포장재',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: '대체',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: '대체',
    serachResultLang: 'ko',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: 'AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'Legal AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: 'Legal AI',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'BHSN',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: 'BHSN',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
  {
    query: 'Blockchain',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'ys.kim@modusign.co.kr',
  },
  {
    query: 'Blockchain',
    serachResultLang: 'en',
    locale: 'ko',
    email: 'anaclumos@gmail.com',
  },
]
