export const subscriptions = [
  // {
  //   query: 'AI',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'kimkj@usc.edu',
  // },
  // {
  //   query: 'Tech Companies',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'kimkj@usc.edu',
  // },
  // {
  //   query: 'junhoyeo',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'i@junho.io',
  // },
  // {
  //   query: 'Pinduoduo',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: '拼多多',
  //   serachResultLang: 'zh',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: 'TEMU marketplace',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'yunjj0223@gmail.com',
  // },
  // {
  //   query: '시스템반도체',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'youjin.ahn@gwanakanalog.com',
  // },
  // {
  //   query: 'Generative AI',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'jungwoolee0419@gmail.com',
  // },
  // {
  //   query: 'Generative AI',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'jungwoolee0419@gmail.com',
  // },
  // {
  //   query: 'Second Hand Marketplace',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'jaewha@gmail.com',
  // },
  // {
  //   query: 'Second Hand Marketplace',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'jaewha@gmail.com',
  // },
  // {
  //   query: 'Second Hand Marketplace',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ron@daangn.com',
  // },
  // {
  //   query: '중고거래',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'jaewha@gmail.com',
  // },
  // {
  //   query: '중고거래',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'ron@daangn.com',
  // },
  // {
  //   query: '시황',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'sunjaeianchoi@gmail.com',
  // },
  // {
  //   query: '경제',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'sunjaeianchoi@gmail.com',
  // },
  // {
  //   query: 'Economy',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'sunjaeianchoi@gmail.com',
  // },
  // {
  //   query: '네트워킹 이벤트',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'sunjaeianchoi@gmail.com',
  // },
  // {
  //   query: '전문연구요원',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'anaclumos@naver.com',
  // },
  // {
  //   query: '친환경',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: '포장재',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: '대체',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: 'AI',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: 'Legal AI',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: 'BHSN',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: 'Blockchain',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ys.kim@modusign.co.kr',
  // },
  // {
  //   query: 'Blockchain',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'wlstjq9608@naver.com',
  // },
  // {
  //   query: 'Layer 0 Blockchain',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'wlstjq9608@naver.com',
  // },
  // {
  //   query: 'Swift Programming Language',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: '1017jennykim@gmail.com',
  // },
  // {
  //   query: 'Swift Programming Language',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: '1017jennykim@gmail.com',
  // },
  // {
  //   query: 'Apple Vision Pro',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: '1017jennykim@gmail.com',
  // },
  // {
  //   query: 'Apple Vision Pro',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: '1017jennykim@gmail.com',
  // },
  // {
  //   query: 'Tesla Motors',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ron@daangn.com',
  // },
  // {
  //   query: 'LLM',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'ron@daangn.com',
  // },
  // {
  //   query: 'Unmanned Aircraft Systems',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'jacobpitsenberger@gmail.com',
  // },
  // {
  //   query: 'Drone Technology',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'jacobpitsenberger@gmail.com',
  // },
  // {
  //   query: 'AI Safety and Governance',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'allisoncyhuang@gmail.com',
  // },
  // {
  //   query: 'AI Safety and Governance',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'anaclumos@naver.com',
  // },
  // {
  //   query: 'Web Analytics',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'liu.z.jonathan@gmail.com',
  // },
  // {
  //   query: 'Scheduling Platform',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'liu.z.jonathan@gmail.com',
  // },
  // {
  //   query: 'OpenAI GPTs App Store',
  //   serachResultLang: 'en',
  //   locale: 'en',
  //   email: 'jameszhou02@gmail.com',
  // },
  // {
  //   query: 'Deep Learning',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'jason002009@gmail.com',
  // },
  // {
  //   query: 'Information Security',
  //   serachResultLang: 'en',
  //   locale: 'ko',
  //   email: 'jason002009@gmail.com',
  // },
  // {
  //   query: '딥러닝',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'jason002009@gmail.com',
  // },
  // {
  //   query: '정보보안',
  //   serachResultLang: 'ko',
  //   locale: 'ko',
  //   email: 'jason002009@gmail.com',
  // },
  // {
  //   query: 'Social Media',
  //   serachResultLang: 'en',
  //   locale: 'zh',
  //   email: 'yazminsbrunch@gmail.com',
  // },
]
