export const log = (message: string, level: 'info' | 'error' = 'info') => {
  if (level === 'error') {
    console.error(message)
  } else {
    console.log(message)
  }
}

export const sanitize = (text: string) => {
  if (!text) return ''
  if (text === 'error') return ''
  return text
    .replaceAll('<script>', '')
    .replaceAll('</script>', '')
    .replaceAll('\n', ' ')
    .replaceAll('\t', ' ')
    .replaceAll('\r', ' ')
    .replaceAll(/<[^>]*>/g, '')
    .replaceAll(/&nbsp;/g, ' ')
    .replaceAll(/&amp;/g, '&')
    .replaceAll(/&quot;/g, '"')
    .replaceAll(/&apos;/g, "'")
    .replaceAll(/&lt;/g, '<')
    .replaceAll(/&gt;/g, '>')
    .replaceAll(/&cent;/g, '¢')
    .replaceAll(/&pound;/g, '£')
    .replaceAll(/&yen;/g, '¥')
    .replaceAll(/&euro;/g, '€')
    .replaceAll(/&copy;/g, '©')
    .replaceAll(/&reg;/g, '®')
    .replaceAll(/&trade;/g, '™')
    .replaceAll(/&times;/g, '×')
    .replaceAll(/&divide;/g, '÷')
    .replaceAll(/&para;/g, '¶')
    .replaceAll(/&sect;/g, '§')
    .replaceAll(/&bull;/g, '•')
    .replaceAll(/&hellip;/g, '…')
    .replaceAll(/&ndash;/g, '–')
    .replaceAll(/&mdash;/g, '—')
    .replaceAll(/&lsquo;/g, '‘')
    .replaceAll(/&rsquo;/g, '’')
    .replaceAll(/&sbquo;/g, '‚')
    .replaceAll(/&ldquo;/g, '“')
    .replaceAll(/&rdquo;/g, '”')
    .replaceAll('\u0000', '')
    .replaceAll('  ', '')
    .replaceAll('\n\n', '\n')
    .replaceAll('Hacker News new | past | comments | ask | show | jobs | submit login', '')
    .replaceAll('Guidelines | FAQ | Lists | API | Security | Legal | Apply to YC | Contact Search:', '')
    .replaceAll('1 hour ago | ', '')
    .replaceAll('2 hours ago | ', '')
    .replaceAll('3 hours ago | ', '')
    .replaceAll('4 hours ago | ', '')
    .replaceAll('5 hours ago | ', '')
    .replaceAll('6 hours ago | ', '')
    .replaceAll('7 hours ago | ', '')
    .replaceAll('8 hours ago | ', '')
    .replaceAll('9 hours ago | ', '')
    .replaceAll('10 hours ago | ', '')
    .replaceAll('11 hours ago | ', '')
    .replaceAll('12 hours ago | ', '')
    .replaceAll('13 hours ago | ', '')
    .replaceAll('14 hours ago | ', '')
    .replaceAll('15 hours ago | ', '')
    .replaceAll('16 hours ago | ', '')
    .replaceAll('17 hours ago | ', '')
    .replaceAll('18 hours ago | ', '')
    .replaceAll('19 hours ago | ', '')
    .replaceAll('20 hours ago | ', '')
    .replaceAll('21 hours ago | ', '')
    .replaceAll('22 hours ago | ', '')
    .replaceAll('23 hours ago | ', '')
    .replaceAll('hide | ', '')
    .replaceAll('past | ', '')
    .replaceAll('favorite | ', '')
    .replaceAll('minutes ago | ', '')
    .replaceAll('minute ago | ', '')
    .replaceAll('parent | ', '')
    .replaceAll('prev | ', '')
    .replaceAll('next [–] ', '')
    .replaceAll('N/A. ', '')
    .replaceAll('N/A.', '')
    .replaceAll('N/A', '')
    .trim()
}
